### ISSUE TITLE
How can use this library with the code i already have?

### ISSUE THREAD

**Issue by pianistprogrammer** [ajaxray/php-watermark#15]
```
        $data = new File();
        $data->name = $request->input('name');
        $this->validate($request, ['file' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048', ] //only allow this type extension file.
        );
        $file = $request->file('file');
        $ext = $file->getClientOriginalExtension();
        $newName = rand(100000, 1001238912) . "." . $ext;
        $file->move('uploads/file', $newName);
        $data->file = $newName;
        $data->save();
```
I am new to Laravel, what I'm doing here is to get a new name for the file and save it to the db as well as to the uploads/file folder. I want to be able to watermark the image i upload as well as retain the naming convention. Example name of the file could be 426240098.jpeg. I'll appreciate your help

**Comment by ajaxray** [comment]
Thanks a lot for asking. And sorry for replying so late.

Basically, it has 2 steps.
1. Include the library using composer.
2. Then, after the file is uploaded, initiate the `Watermark` object using that file path.
```
$watermark = new Watermark(realpath('uploads/file/'.$newName));
// Then follow along with setting options and generating output 
```
If you want to overwrite the uploaded file itself, ignore the 2nd parameter in for `Watermark::withImage()` and `Watermark::withText()` function. Otherwise,
prepare a name before executing watermark generation. For example:
```
$newWatermarkedName = 'watermarked_'. $newName;
$watermark->withImage('path/to/logo.png', realpath('uploads/file/'.$newWatermarkedName));
```

Please let me know if anymore clarification may help you. Otherwise, please don't forget to close the issue.
