### ISSUE TITLE
pdf quality is distorted,

### ISSUE THREAD

**Issue by jigo3068** [ajaxray/php-watermark#16]
Hi friend

I have used your library for pdf watermark and it would be working well but pdf quality is distorted, can you please guide me how to make it same as original with watermark.

Thanks!
Jigs

**Comment by ajaxray** [comment]
When using the imagemagick + ghostscript extraction and joining pdf pages, it has a few drawbacks including file-size issue. Many developers were asking for a solution about the file size and PDF quality since releasing of this library.
So, I've created a command line tool for PDF watermarking that will work without converting pages into images. As a result, you'll get better PDF quality and dramatically less file size.

https://github.com/ajaxray/markpdf

Please download, check and let me know your feedback.
